"""added username

Revision ID: 337180a9353a
Revises: bcb3c33aeecc
Create Date: 2023-11-29 23:17:34.506779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337180a9353a'
down_revision = 'bcb3c33aeecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
